/**
 * Dữ liệu gốc: giữ nguyên toàn bộ tọa độ, node và cạnh đang hoạt động.
 * B09/B14/B15 cố ý không tham gia dẫn đường (routingEnabled: false).
 * B12_CUA1/B12_CUA2/B13_LOIVAO là lối vào, được đi qua để tới đích.
 * Tọa độ tầng trên dùng ảnh khuôn viên, chỉ là sơ đồ minh họa.
 * Không có bản vẽ nội thất đã được kiểm chứng trong INDOOR_PLANS.
 * Xem CONFIG-GUIDE.md trước khi thay đổi lối đi.
 */
const MAP_IMAGE = {
  src: MAP_BACKGROUND_DATA_URL,
  width: 1000,
  height: 1298,
};

const HOSPITAL_MAP = {
  nodes: [
    { id: "G_1A", name: "Cổng 1A",         x: 527, y: 388, floor: 1, isGate: true },
    { id: "G_1B", name: "Cổng 1B",         x: 350, y: 330, floor: 1, isGate: true },
    { id: "G_CC", name: "Cổng Cấp cứu",    x: 112, y: 486, floor: 1, isGate: true },
    { id: "G_5",  name: "Cổng số 5",       x: 124, y: 1030, floor: 1, isGate: true },

    { id: "B01", name: "Nhà N1A",                              x: 296, y: 386,  floor: 1, isDestination: true, isTransitPoint: true },
    { id: "B02", name: "Nhà N1B",                              x: 422, y: 386,  floor: 1, isDestination: true, isTransitPoint: true },
    { id: "B03", name: "Nhà N2A",                              x: 374, y: 448,  floor: 1, isDestination: true, isTransitPoint: true },
    { id: "B04", name: "Nhà N2B",                              x: 413, y: 437,  floor: 1, isDestination: true, isTransitPoint: true },
    { id: "B05", name: "Trung tâm máy gia tốc",                x: 226, y: 460,  floor: 1, isDestination: true, isTransitPoint: true },
    { id: "B06", name: "Nhà N3",                                x: 472, y: 520,  floor: 1, isDestination: true, isTransitPoint: true },
    { id: "B07", name: "Trung tâm thẩm mỹ",                    x: 609, y: 422,  floor: 1, isDestination: true, isTransitPoint: true },
    { id: "B08", name: "Tòa Tháp đôi",                          x: 220, y: 675,  floor: 1, isDestination: true, isTransitPoint: true },
    { id: "B09", name: "Viện Bảo vệ, chăm sóc SK cán bộ TW",    x: 496, y: 607,  floor: 1, isDestination: true, isTransitPoint: true, routingEnabled: false },
    { id: "B10", name: "Nhà Chỉ huy cơ quan",                   x: 496, y: 747,  floor: 1, isDestination: true, isTransitPoint: true },
    { id: "B11", name: "Viện Lâm sàng các bệnh truyền nhiễm",  x: 299, y: 920,  floor: 1, isDestination: true, isTransitPoint: true },
    { id: "B12", name: "Nhà để xe nhân viên",                   x: 176, y: 970,  floor: 1, isDestination: true, isTransitPoint: true },
    { id: "B13", name: "Nhà lưu trú",                           x: 165, y: 904,  floor: 1, isDestination: true, isTransitPoint: true },
    { id: "B14", name: "Nhà thể thao đa năng (1)",              x: 618, y: 634,  floor: 1, isDestination: true, isTransitPoint: true, routingEnabled: false },
    { id: "B15", name: "Nhà thể thao đa năng (2)",              x: 588, y: 750,  floor: 1, isDestination: true, isTransitPoint: true, routingEnabled: false },
    { id: "B16", name: "Nhà tang lễ",                           x: 353, y: 1129, floor: 1, isDestination: true, isTransitPoint: true },

    { id: "B01_F2_1", name: "Hành lang Tầng 2", x: 256, y: 400, floor: 2, isWaypoint: true },
    { id: "B01_F2_2", name: "Hành lang Tầng 2", x: 276, y: 399, floor: 2, isWaypoint: true },
    { id: "B01_F2_3", name: "Hành lang Tầng 2", x: 294, y: 398, floor: 2, isWaypoint: true },
    { id: "B01_F2_4", name: "Hành lang Tầng 2", x: 311, y: 399, floor: 2, isWaypoint: true },
    { id: "B01_F2_5", name: "Hành lang Tầng 2", x: 326, y: 398, floor: 2, isWaypoint: true },
    { id: "B01_F3_1", name: "Hành lang Tầng 3", x: 256, y: 400, floor: 3, isWaypoint: true },
    { id: "B01_F3_2", name: "Hành lang Tầng 3", x: 276, y: 399, floor: 3, isWaypoint: true },
    { id: "B01_F3_3", name: "Hành lang Tầng 3", x: 294, y: 398, floor: 3, isWaypoint: true },
    { id: "B01_F3_4", name: "Hành lang Tầng 3", x: 311, y: 399, floor: 3, isWaypoint: true },
    { id: "B01_F3_5", name: "Hành lang Tầng 3", x: 326, y: 398, floor: 3, isWaypoint: true },
    { id: "B01_F4_1", name: "Hành lang Tầng 4", x: 256, y: 400, floor: 4, isWaypoint: true },
    { id: "B01_F4_2", name: "Hành lang Tầng 4", x: 276, y: 399, floor: 4, isWaypoint: true },
    { id: "B01_F4_3", name: "Hành lang Tầng 4", x: 294, y: 398, floor: 4, isWaypoint: true },
    { id: "B01_F4_4", name: "Hành lang Tầng 4", x: 311, y: 399, floor: 4, isWaypoint: true },
    { id: "B01_F4_5", name: "Hành lang Tầng 4", x: 326, y: 398, floor: 4, isWaypoint: true },

    { id: "B02_F2_1", name: "Hành lang Tầng 2", x: 400, y: 397, floor: 2, isWaypoint: true },
    { id: "B02_F2_2", name: "Hành lang Tầng 2", x: 414, y: 397, floor: 2, isWaypoint: true },
    { id: "B02_F2_3", name: "Hành lang Tầng 2", x: 430, y: 399, floor: 2, isWaypoint: true },
    { id: "B02_F2_4", name: "Hành lang Tầng 2", x: 448, y: 401, floor: 2, isWaypoint: true },
    { id: "B02_F2_5", name: "Hành lang Tầng 2", x: 466, y: 410, floor: 2, isWaypoint: true },
    { id: "B02_F2_6", name: "Hành lang Tầng 2", x: 482, y: 418, floor: 2, isWaypoint: true },
    { id: "B02_F3_1", name: "Hành lang Tầng 3", x: 400, y: 397, floor: 3, isWaypoint: true },
    { id: "B02_F3_2", name: "Hành lang Tầng 3", x: 414, y: 397, floor: 3, isWaypoint: true },
    { id: "B02_F3_3", name: "Hành lang Tầng 3", x: 430, y: 399, floor: 3, isWaypoint: true },
    { id: "B02_F3_4", name: "Hành lang Tầng 3", x: 448, y: 401, floor: 3, isWaypoint: true },
    { id: "B02_F3_5", name: "Hành lang Tầng 3", x: 466, y: 410, floor: 3, isWaypoint: true },
    { id: "B02_F3_6", name: "Hành lang Tầng 3", x: 482, y: 418, floor: 3, isWaypoint: true },
    { id: "B02_F4_1", name: "Hành lang Tầng 4", x: 400, y: 397, floor: 4, isWaypoint: true },
    { id: "B02_F4_2", name: "Hành lang Tầng 4", x: 414, y: 397, floor: 4, isWaypoint: true },
    { id: "B02_F4_3", name: "Hành lang Tầng 4", x: 430, y: 399, floor: 4, isWaypoint: true },
    { id: "B02_F4_4", name: "Hành lang Tầng 4", x: 448, y: 401, floor: 4, isWaypoint: true },
    { id: "B02_F4_5", name: "Hành lang Tầng 4", x: 466, y: 410, floor: 4, isWaypoint: true },
    { id: "B02_F4_6", name: "Hành lang Tầng 4", x: 482, y: 418, floor: 4, isWaypoint: true },

    { id: "B03_F2_1", name: "Hành lang Tầng 2", x: 355, y: 412, floor: 2, isWaypoint: true },
    { id: "B03_F2_2", name: "Hành lang Tầng 2", x: 350, y: 428, floor: 2, isWaypoint: true },
    { id: "B03_F2_3", name: "Hành lang Tầng 2", x: 356, y: 442, floor: 2, isWaypoint: true },
    { id: "B03_F2_4", name: "Hành lang Tầng 2", x: 355, y: 462, floor: 2, isWaypoint: true },
    { id: "B03_F3_1", name: "Hành lang Tầng 3", x: 355, y: 412, floor: 3, isWaypoint: true },
    { id: "B03_F3_2", name: "Hành lang Tầng 3", x: 350, y: 428, floor: 3, isWaypoint: true },
    { id: "B03_F3_3", name: "Hành lang Tầng 3", x: 356, y: 442, floor: 3, isWaypoint: true },
    { id: "B03_F3_4", name: "Hành lang Tầng 3", x: 355, y: 462, floor: 3, isWaypoint: true },
    { id: "B03_F4_1", name: "Hành lang Tầng 4", x: 355, y: 412, floor: 4, isWaypoint: true },
    { id: "B03_F4_2", name: "Hành lang Tầng 4", x: 350, y: 428, floor: 4, isWaypoint: true },
    { id: "B03_F4_3", name: "Hành lang Tầng 4", x: 356, y: 442, floor: 4, isWaypoint: true },
    { id: "B03_F4_4", name: "Hành lang Tầng 4", x: 355, y: 462, floor: 4, isWaypoint: true },

    { id: "B06_F2_1", name: "Hành lang Tầng 2", x: 414, y: 506, floor: 2, isWaypoint: true },
    { id: "B06_F2_2", name: "Hành lang Tầng 2", x: 436, y: 506, floor: 2, isWaypoint: true },
    { id: "B06_F2_3", name: "Hành lang Tầng 2", x: 459, y: 506, floor: 2, isWaypoint: true },
    { id: "B06_F2_4", name: "Hành lang Tầng 2", x: 477, y: 506, floor: 2, isWaypoint: true },
    { id: "B06_F2_5", name: "Hành lang Tầng 2", x: 494, y: 506, floor: 2, isWaypoint: true },
    { id: "B06_F2_6", name: "Hành lang Tầng 2", x: 520, y: 506, floor: 2, isWaypoint: true },
    { id: "B06_F2_7", name: "Hành lang Tầng 2", x: 546, y: 505, floor: 2, isWaypoint: true },
    { id: "B06_F3_1", name: "Hành lang Tầng 3", x: 414, y: 506, floor: 3, isWaypoint: true },
    { id: "B06_F3_2", name: "Hành lang Tầng 3", x: 436, y: 506, floor: 3, isWaypoint: true },
    { id: "B06_F3_3", name: "Hành lang Tầng 3", x: 459, y: 506, floor: 3, isWaypoint: true },
    { id: "B06_F3_4", name: "Hành lang Tầng 3", x: 477, y: 506, floor: 3, isWaypoint: true },
    { id: "B06_F3_5", name: "Hành lang Tầng 3", x: 494, y: 506, floor: 3, isWaypoint: true },
    { id: "B06_F3_6", name: "Hành lang Tầng 3", x: 520, y: 506, floor: 3, isWaypoint: true },
    { id: "B06_F3_7", name: "Hành lang Tầng 3", x: 546, y: 505, floor: 3, isWaypoint: true },
    { id: "B06_F4_1", name: "Hành lang Tầng 4", x: 414, y: 506, floor: 4, isWaypoint: true },
    { id: "B06_F4_2", name: "Hành lang Tầng 4", x: 436, y: 506, floor: 4, isWaypoint: true },
    { id: "B06_F4_3", name: "Hành lang Tầng 4", x: 459, y: 506, floor: 4, isWaypoint: true },
    { id: "B06_F4_4", name: "Hành lang Tầng 4", x: 477, y: 506, floor: 4, isWaypoint: true },
    { id: "B06_F4_5", name: "Hành lang Tầng 4", x: 494, y: 506, floor: 4, isWaypoint: true },
    { id: "B06_F4_6", name: "Hành lang Tầng 4", x: 520, y: 506, floor: 4, isWaypoint: true },
    { id: "B06_F4_7", name: "Hành lang Tầng 4", x: 546, y: 505, floor: 4, isWaypoint: true },

    { id: "P_G1", name: "Lối đi gần Nhà N1A", x: 324, y: 310, floor: 1, isWaypoint: true, isQRPoint: true },
    { id: "P_G2", name: "Lối đi gần Nhà N1B", x: 409, y: 338, floor: 1, isWaypoint: true, isQRPoint: true },
    { id: "P_G3", name: "Lối đi", x: 374, y: 338, floor: 1, isWaypoint: true },
    { id: "P_G4", name: "Lối đi", x: 374, y: 380, floor: 1, isWaypoint: true },
    { id: "P_G5", name: "Lối đi", x: 226, y: 380, floor: 1, isWaypoint: true },
    { id: "P_G6", name: "Lối đi", x: 326, y: 380, floor: 1, isWaypoint: true },
    { id: "P_G7", name: "Lối đi", x: 351, y: 380, floor: 1, isWaypoint: true },
    { id: "P_G8", name: "Lối đi", x: 526, y: 394, floor: 1, isWaypoint: true },
    { id: "P_G9", name: "Lối đi", x: 591, y: 408, floor: 1, isWaypoint: true },
    { id: "P_G10", name: "Lối đi", x: 222, y: 423, floor: 1, isWaypoint: true },
    { id: "P_G12", name: "Lối đi", x: 348, y: 428, floor: 1, isWaypoint: true },
    { id: "P_G13", name: "Lối đi", x: 381, y: 429, floor: 1, isWaypoint: true },
    { id: "P_G14", name: "Lối đi gần Nhà N1A", x: 320, y: 430, floor: 1, isWaypoint: true, isQRPoint: true },
    { id: "P_G15", name: "Lối đi", x: 528, y: 454, floor: 1, isWaypoint: true },
    { id: "P_G16", name: "Lối đi gần Nhà N3", x: 495, y: 456, floor: 1, isWaypoint: true, isQRPoint: true },
    { id: "P_G17", name: "Lối đi gần Nhà N2B", x: 412, y: 458, floor: 1, isWaypoint: true, isQRPoint: true },
    { id: "P_G18", name: "Lối đi", x: 218, y: 461, floor: 1, isWaypoint: true },
    { id: "P_G19", name: "Lối đi gần Cổng Cấp cứu", x: 116, y: 484, floor: 1, isWaypoint: true, isQRPoint: true },
    { id: "P_G20", name: "Lối đi", x: 218, y: 487, floor: 1, isWaypoint: true },
    { id: "P_G21", name: "Lối đi gần Nhà N2A", x: 354, y: 514, floor: 1, isWaypoint: true, isQRPoint: true },
    { id: "P_G22", name: "Lối đi", x: 185, y: 548, floor: 1, isWaypoint: true },
    { id: "P_G23", name: "Lối đi", x: 219, y: 548, floor: 1, isWaypoint: true },
    { id: "P_G24", name: "Lối đi", x: 359, y: 550, floor: 1, isWaypoint: true },
    { id: "P_G25", name: "Lối đi", x: 394, y: 550, floor: 1, isWaypoint: true },
    { id: "P_G26", name: "Lối đi gần Cổng Cấp cứu", x: 142, y: 552, floor: 1, isWaypoint: true, isQRPoint: true },
    { id: "P_G27", name: "Lối đi gần Viện Bảo vệ, chăm sóc SK cán bộ TW", x: 360, y: 588, floor: 1, isWaypoint: true, isQRPoint: true },
    { id: "P_G28", name: "Lối đi", x: 392, y: 644, floor: 1, isWaypoint: true },
    { id: "P_G29", name: "Lối đi", x: 361, y: 646, floor: 1, isWaypoint: true },
    { id: "P_G30", name: "Lối đi", x: 290, y: 678, floor: 1, isWaypoint: true },
    { id: "P_G31", name: "Lối đi", x: 360, y: 704, floor: 1, isWaypoint: true },
    { id: "P_G32", name: "Lối đi", x: 392, y: 705, floor: 1, isWaypoint: true },
    { id: "P_G36", name: "Lối đi gần Nhà Chỉ huy cơ quan", x: 495, y: 710, floor: 1, isWaypoint: true, isQRPoint: true },
    { id: "P_G37", name: "Lối đi", x: 358, y: 773, floor: 1, isWaypoint: true },
    { id: "P_G38", name: "Lối đi", x: 358, y: 802, floor: 1, isWaypoint: true },
    { id: "P_G39", name: "Lối đi", x: 393, y: 800, floor: 1, isWaypoint: true },
    { id: "P_G40", name: "Lối đi", x: 182, y: 808, floor: 1, isWaypoint: true },
    { id: "P_G41", name: "Lối đi", x: 204, y: 808, floor: 1, isWaypoint: true },
    { id: "P_G42", name: "Lối đi gần Viện Lâm sàng các bệnh truyền nhiễm", x: 376, y: 890, floor: 1, isWaypoint: true, isQRPoint: true },
    { id: "P_G43", name: "Lối đi gần Nhà lưu trú", x: 202, y: 895, floor: 1, isWaypoint: true, isQRPoint: true },
    { id: "P_G44", name: "Lối đi gần Viện Lâm sàng các bệnh truyền nhiễm", x: 302, y: 894, floor: 1, isWaypoint: true, isQRPoint: true },
    { id: "P_G45", name: "Lối đi", x: 162, y: 926, floor: 1, isWaypoint: true },
    { id: "P_G46", name: "Lối đi gần Nhà để xe nhân viên", x: 200, y: 928, floor: 1, isWaypoint: true, isQRPoint: true },
    { id: "P_G47", name: "Lối đi", x: 290, y: 1030, floor: 1, isWaypoint: true },
    { id: "P_G48", name: "Lối đi gần Nhà để xe nhân viên", x: 136, y: 1030, floor: 1, isWaypoint: true, isQRPoint: true },
    { id: "P_G49", name: "Lối đi gần Nhà để xe nhân viên", x: 195, y: 1031, floor: 1, isWaypoint: true, isQRPoint: true },
    { id: "P_G50", name: "Lối đi gần Nhà tang lễ", x: 292, y: 1126, floor: 1, isWaypoint: true, isQRPoint: true },
    { id: "P_G51", name: "Lối đi", x: 346, y: 1127, floor: 1, isWaypoint: true },

	{ id: "P_G61", name: "Lối đi ngã 3 cấp cứu, trung tâm gia tốc", x: 220, y: 550, floor: 1, isWaypoint: true },
    { id: "P_G55", name: "Lối đi", x: 610, y: 700, floor: 1, isWaypoint: true },

	{ id: "P_G62", name: "Lối đi", x: 183, y: 611, floor: 1, isWaypoint: true },
	{ id: "P_G63", name: "Lối đi", x: 183, y: 669, floor: 1, isWaypoint: true },
	{ id: "P_G64", name: "Lối đi", x: 183, y: 730, floor: 1, isWaypoint: true },
	{ id: "P_G65", name: "Lối đi", x: 523, y: 605, floor: 1, isWaypoint: true },
	{ id: "P_G66", name: "Lối đi", x: 458, y: 376, floor: 1, isWaypoint: true },
	{ id: "P_G67", name: "Lối đi", x: 394, y: 337, floor: 1, isWaypoint: true },

    { id: "B_XEMAY", name: "Nhà để xe máy", x: 317, y: 311, floor: 1, isDestination: true },
    { id: "B01_CUA1", name: "Lối vào 1 (Nhà N1A)", x: 310, y: 388, floor: 1, isDestination: true, isTransitPoint: true },
    { id: "B12_CUA1", name: "Lối vào 1 (Nhà để xe nhân viên)", x: 150, y: 1004, floor: 1, isDestination: true, isTransitPoint: true },
    { id: "B12_CUA2", name: "Lối vào 2 (Nhà để xe nhân viên)", x: 179, y: 941, floor: 1, isDestination: true, isTransitPoint: true },
    { id: "B01_CUA2", name: "Lối vào 2 (Nhà N1A)", x: 304, y: 420, floor: 1, isDestination: true, isTransitPoint: true },
    { id: "B02_CUA1", name: "Lối vào 1 (Nhà N1B)", x: 381, y: 387, floor: 1, isDestination: true, isTransitPoint: true },
    { id: "B02_CUA2", name: "Lối vào 2 (Nhà N1B)", x: 380, y: 418, floor: 1, isDestination: true, isTransitPoint: true },
    { id: "B02_CUA3", name: "Lối vào 3 (Nhà N1B)", x: 458, y: 442, floor: 1, isDestination: true, isTransitPoint: true },
    { id: "B03_TB1", name: "Thang bộ 1 (Nhà N2A)", x: 328, y: 399, floor: 1, isDestination: true, isTransitPoint: true },
    { id: "B03_TB2", name: "Thang bộ 2 (Nhà N2A)", x: 382, y: 400, floor: 1, isDestination: true, isTransitPoint: true },
    { id: "B06_CUA", name: "Lối vào (Nhà N3)", x: 490, y: 491, floor: 1, isDestination: true, isTransitPoint: true },
    { id: "B08_SANHA", name: "Sảnh A (Toà Tháp đôi)", x: 259, y: 687, floor: 1, isDestination: true, isTransitPoint: true },
    { id: "B08_SANHB", name: "Sảnh B (Toà Tháp đôi)", x: 188, y: 773, floor: 1, isDestination: true, isTransitPoint: true },
    { id: "B08_SANHC", name: "Sảnh C (Toà Tháp đôi)", x: 183, y: 570, floor: 1, isDestination: true, isTransitPoint: true },
    { id: "B01_F1_THUOC", name: "Nhà thuốc số 2 (Nhà N1A, Tầng 1)", x: 257, y: 399, floor: 1, isDestination: true, isTransitPoint: true },
    { id: "B01_F1_DKKD", name: "Khu đăng ký khám dịch vụ (Nhà N1A, Tầng 1)", x: 294, y: 390, floor: 1, isDestination: true, isTransitPoint: true },
    { id: "B01_F1_BHYT", name: "Khu đăng ký khám BHYT (Nhà N1A, Tầng 1)", x: 311, y: 398, floor: 1, isDestination: true, isTransitPoint: true },
    { id: "B01_F1_HD", name: "Khu hướng dẫn (Nhà N1A, Tầng 1)", x: 327, y: 398, floor: 1, isDestination: true, isTransitPoint: true },
    { id: "B01_F1_TT", name: "Khu thanh toán (Nhà N1A, Tầng 1)", x: 285, y: 406, floor: 1, isDestination: true, isTransitPoint: true },

    { id: "B02_F1_XQUANG", name: "Khu vực Xquang (Nhà N1B, Tầng 1)", x: 400, y: 397, floor: 1, isDestination: true, isTransitPoint: true },
    { id: "B02_F1_MRI", name: "Khu vực Cộng hưởng từ MRI (Nhà N1B, Tầng 1)", x: 461, y: 415, floor: 1, isDestination: true, isTransitPoint: true },

    { id: "B03_F1_BHYT", name: "Khu vực cấp phát thuốc BHYT (Nhà N2A, Tầng 1)", x: 337, y: 440, floor: 1, isDestination: true, isTransitPoint: true },

    { id: "B06_F1_XQUANG", name: "Khu vực Xquang, điện tim, siêu âm (Nhà N3, Tầng 1)", x: 521, y: 507, floor: 1, isDestination: true, isTransitPoint: true },
    { id: "B06_TM", name: "Thang máy (Nhà N3)", x: 478, y: 507, floor: 1, isDestination: true },
    { id: "B06_TB", name: "Thang bộ (Nhà N3)", x: 506, y: 497, floor: 1, isDestination: true, isTransitPoint: true },

    { id: "B08_CAPCUU", name: "Khu Cấp cứu C1.3 (Toà Tháp đôi)", x: 142, y: 566, floor: 1, isDestination: true, isTransitPoint: false },
    { id: "B08_KHAMA", name: "Khu khám A - Bộ đội hưu và Viettel (Toà Tháp đôi)", x: 209, y: 592, floor: 1, isDestination: true, isTransitPoint: false },
    { id: "B08_NGOAIKHOA", name: "Nhà Ngoại khoa (Toà Tháp đôi)", x: 237, y: 593, floor: 1, isDestination: true, isTransitPoint: false },
    { id: "B08_TM_NGOAIKHOA", name: "Thang máy Nhà Ngoại khoa (Toà Tháp đôi)", x: 200, y: 628, floor: 1, isDestination: true, isTransitPoint: true },
    { id: "B08_TM_CANLAMSANG", name: "Khối nhà Cận lâm sàng - thang máy (Toà Tháp đôi)", x: 167, y: 669, floor: 1, isDestination: true, isTransitPoint: true },
    { id: "B08_SANHCHINH", name: "Sảnh chính Toà Tháp đôi", x: 235, y: 670, floor: 1, isDestination: true, isTransitPoint: true },
    { id: "B08_KHAMB", name: "Khu khám B, khu thanh toán (Toà Tháp đôi)", x: 209, y: 729, floor: 1, isDestination: true, isTransitPoint: false },
    { id: "B08_NHATHUOC1", name: "Nhà thuốc số 1 (Toà Tháp đôi)", x: 144, y: 717, floor: 1, isDestination: true, isTransitPoint: false },
    { id: "B08_NOIKHOA", name: "Nhà Nội khoa (Toà Tháp đôi)", x: 237, y: 733, floor: 1, isDestination: true, isTransitPoint: false },
    { id: "B08_TM_NOIKHOA", name: "Thang máy Nhà Nội khoa (Toà Tháp đôi)", x: 200, y: 705, floor: 1, isDestination: true, isTransitPoint: true },

    { id: "B10_SANHA", name: "Sảnh A (Nhà Chỉ huy cơ quan)", x: 497, y: 726, floor: 1, isDestination: true },

    { id: "B13_LOIVAO", name: "Lối vào Nhà lưu trú", x: 164, y: 916, floor: 1, isDestination: true, isTransitPoint: true },
  ],

  edges: [
    { from: "B01_F1_THUOC", to: "B01_F1_DKKD" },
    { from: "B01_F1_DKKD", to: "B01_F1_BHYT" },
    { from: "B01_F1_BHYT", to: "B01_F1_HD" },
    { from: "B01_F1_HD", to: "B01_F1_TT" },
    { from: "B01", to: "B01_F1_DKKD" },
    { from: "B01_F1_HD", to: "B01_F2_5", isElevator: true, instruction: "Đi thang máy/thang bộ (cạnh Khu hướng dẫn) lên Tầng 2 - Nhà N1A" },
    { from: "B01_F1_DKKD", to: "B01_F2_5", isElevator: true, instruction: "Đi thang máy/thang bộ (cạnh Khu đăng ký khám dịch vụ) lên Tầng 2 - Nhà N1A" },
    { from: "B02_F1_XQUANG", to: "B02_F1_MRI" },
    { from: "B02", to: "B02_F1_XQUANG" },
    { from: "B02_F1_XQUANG", to: "B02_F2_6", isElevator: true, instruction: "Đi thang bộ lên Tầng 2 - Nhà N1B" },
    { from: "B03", to: "B03_F1_BHYT" },
    { from: "B03_F1_BHYT", to: "B03_F2_4", isElevator: true, instruction: "Đi thang máy/thang bộ lên Tầng 2 - Nhà N2A" },

	{ from: "B05", to: "P_G18" },

    { from: "B06", to: "B06_F1_XQUANG" },
    { from: "B06_F1_XQUANG", to: "B06_TB" },
    { from: "B06_TB", to: "B06_TM" },
    { from: "B06_TM", to: "B06_F2_7", isElevator: true, instruction: "Đi thang máy lên Tầng 2 - Nhà N3" },
    { from: "B08_KHAMA", to: "B08_NGOAIKHOA" },
    { from: "B08_NGOAIKHOA", to: "B08_TM_NGOAIKHOA" },
    { from: "B08_TM_NGOAIKHOA", to: "B08_TM_CANLAMSANG" },
    { from: "B08_TM_CANLAMSANG", to: "B08_SANHCHINH" },
    { from: "B08_SANHCHINH", to: "B08_KHAMB" },
    { from: "B08_KHAMB", to: "B08_NOIKHOA" },
    { from: "B08_NOIKHOA", to: "B08_TM_NOIKHOA" },
    { from: "B08", to: "B08_SANHCHINH" },
    { from: "B10", to: "B10_SANHA" },

	{ from: "B13_LOIVAO", to: "B13" },
    { from: "B01_F2_1", to: "B01_F2_2" },
    { from: "B01_F2_2", to: "B01_F2_3" },
    { from: "B01_F2_3", to: "B01_F2_4" },
    { from: "B01_F2_4", to: "B01_F2_5" },
    { from: "B01_F3_1", to: "B01_F3_2" },
    { from: "B01_F3_2", to: "B01_F3_3" },
    { from: "B01_F3_3", to: "B01_F3_4" },
    { from: "B01_F3_4", to: "B01_F3_5" },
    { from: "B01_F2_5", to: "B01_F3_5", isElevator: true, instruction: "Đi thang máy/cầu thang lên Tầng 3 - Nhà N1A" },
    { from: "B01_F4_1", to: "B01_F4_2" },
    { from: "B01_F4_2", to: "B01_F4_3" },
    { from: "B01_F4_3", to: "B01_F4_4" },
    { from: "B01_F4_4", to: "B01_F4_5" },
    { from: "B01_F3_5", to: "B01_F4_5", isElevator: true, instruction: "Đi thang máy/cầu thang lên Tầng 4 - Nhà N1A" },
    { from: "B02_F2_1", to: "B02_F2_2" },
    { from: "B02_F2_2", to: "B02_F2_3" },
    { from: "B02_F2_3", to: "B02_F2_4" },
    { from: "B02_F2_4", to: "B02_F2_5" },
    { from: "B02_F2_5", to: "B02_F2_6" },
    { from: "B02_F3_1", to: "B02_F3_2" },
    { from: "B02_F3_2", to: "B02_F3_3" },
    { from: "B02_F3_3", to: "B02_F3_4" },
    { from: "B02_F3_4", to: "B02_F3_5" },
    { from: "B02_F3_5", to: "B02_F3_6" },
    { from: "B02_F2_6", to: "B02_F3_6", isElevator: true, instruction: "Đi thang máy/cầu thang lên Tầng 3 - Nhà N1B" },
    { from: "B02_F4_1", to: "B02_F4_2" },
    { from: "B02_F4_2", to: "B02_F4_3" },
    { from: "B02_F4_3", to: "B02_F4_4" },
    { from: "B02_F4_4", to: "B02_F4_5" },
    { from: "B02_F4_5", to: "B02_F4_6" },
    { from: "B02_F3_6", to: "B02_F4_6", isElevator: true, instruction: "Đi thang máy/cầu thang lên Tầng 4 - Nhà N1B" },
    { from: "B03_F2_1", to: "B03_F2_2" },
    { from: "B03_F2_2", to: "B03_F2_3" },
    { from: "B03_F2_3", to: "B03_F2_4" },
    { from: "B03_F3_1", to: "B03_F3_2" },
    { from: "B03_F3_2", to: "B03_F3_3" },
    { from: "B03_F3_3", to: "B03_F3_4" },
    { from: "B03_F2_4", to: "B03_F3_4", isElevator: true, instruction: "Đi thang máy/cầu thang lên Tầng 3 - Nhà N2A" },
    { from: "B03_F4_1", to: "B03_F4_2" },
    { from: "B03_F4_2", to: "B03_F4_3" },
    { from: "B03_F4_3", to: "B03_F4_4" },
    { from: "B03_F3_4", to: "B03_F4_4", isElevator: true, instruction: "Đi thang máy/cầu thang lên Tầng 4 - Nhà N2A" },
    { from: "B06_F2_1", to: "B06_F2_2" },
    { from: "B06_F2_2", to: "B06_F2_3" },
    { from: "B06_F2_3", to: "B06_F2_4" },
    { from: "B06_F2_4", to: "B06_F2_5" },
    { from: "B06_F2_5", to: "B06_F2_6" },
    { from: "B06_F2_6", to: "B06_F2_7" },
    { from: "B06_F3_1", to: "B06_F3_2" },
    { from: "B06_F3_2", to: "B06_F3_3" },
    { from: "B06_F3_3", to: "B06_F3_4" },
    { from: "B06_F3_4", to: "B06_F3_5" },
    { from: "B06_F3_5", to: "B06_F3_6" },
    { from: "B06_F3_6", to: "B06_F3_7" },
    { from: "B06_F2_7", to: "B06_F3_7", isElevator: true, instruction: "Đi thang máy/cầu thang lên Tầng 3 - Nhà N3" },
    { from: "B06_F4_1", to: "B06_F4_2" },
    { from: "B06_F4_2", to: "B06_F4_3" },
    { from: "B06_F4_3", to: "B06_F4_4" },
    { from: "B06_F4_4", to: "B06_F4_5" },
    { from: "B06_F4_5", to: "B06_F4_6" },
    { from: "B06_F4_6", to: "B06_F4_7" },
    { from: "B06_F3_7", to: "B06_F4_7", isElevator: true, instruction: "Đi thang máy/cầu thang lên Tầng 4 - Nhà N3" },
    { from: "P_G1", to: "P_G2" },
    { from: "P_G1", to: "P_G3" },
    { from: "P_G1", to: "P_G4" },
    { from: "P_G1", to: "P_G6" },
    { from: "P_G1", to: "P_G7" },
    { from: "P_G2", to: "P_G3" },
    { from: "P_G2", to: "P_G4" },
    { from: "P_G2", to: "P_G7" },
	{ from: "P_G2", to: "P_G66" },
    { from: "P_G3", to: "P_G4" },
    { from: "P_G3", to: "P_G6" },
    { from: "P_G3", to: "P_G7" },
    { from: "P_G4", to: "P_G6" },
    { from: "P_G4", to: "P_G7" },
    { from: "P_G4", to: "P_G12" },
    { from: "P_G4", to: "P_G13" },
    { from: "P_G4", to: "P_G14" },
    { from: "P_G4", to: "P_G17" },
    { from: "P_G5", to: "P_G10" },
    { from: "P_G6", to: "P_G7" },
    { from: "P_G6", to: "P_G12" },
    { from: "P_G6", to: "P_G13" },
    { from: "P_G6", to: "P_G14" },
    { from: "P_G7", to: "P_G12" },
    { from: "P_G7", to: "P_G13" },
    { from: "P_G7", to: "P_G14" },
    { from: "P_G8", to: "P_G9" },
    { from: "P_G8", to: "P_G15" },
    { from: "P_G8", to: "P_G16" },
	{ from: "P_G8", to: "P_G66" },
    { from: "P_G10", to: "P_G18" },
    { from: "P_G12", to: "P_G13" },
    { from: "P_G12", to: "P_G14" },
    { from: "P_G12", to: "P_G17" },
    { from: "P_G12", to: "P_G21" },
    { from: "P_G13", to: "P_G14" },
    { from: "P_G13", to: "P_G17" },
    { from: "P_G13", to: "P_G21" },
    { from: "P_G15", to: "P_G16" },
    { from: "P_G16", to: "P_G17" },
    { from: "P_G17", to: "P_G21" },
    { from: "P_G18", to: "P_G20" },
    { from: "P_G19", to: "P_G20" },
    { from: "P_G20", to: "P_G23" },
    { from: "P_G21", to: "P_G24" },
    { from: "P_G21", to: "P_G25" },
    { from: "P_G22", to: "P_G23" },
    { from: "P_G22", to: "P_G26" },
    { from: "P_G24", to: "P_G25" },
    { from: "P_G24", to: "P_G27" },
    { from: "P_G24", to: "P_G23" },
    { from: "P_G27", to: "P_G28" },
    { from: "P_G27", to: "P_G29" },
    { from: "P_G28", to: "P_G29" },
    { from: "P_G28", to: "P_G31" },
    { from: "P_G28", to: "P_G32" },
    { from: "P_G29", to: "P_G31" },
    { from: "P_G27", to: "P_G30" },
    { from: "P_G29", to: "P_G32" },
    { from: "P_G30", to: "P_G37" },
    { from: "P_G31", to: "P_G32" },
    { from: "P_G31", to: "P_G37" },
    { from: "P_G32", to: "P_G36" },
    { from: "P_G37", to: "P_G38" },
    { from: "P_G38", to: "P_G39" },
    { from: "P_G38", to: "P_G42" },
    { from: "P_G39", to: "P_G42" },
    { from: "P_G40", to: "P_G41" },
    { from: "P_G41", to: "P_G38" },
    { from: "P_G41", to: "P_G43" },
    { from: "P_G42", to: "P_G44" },
    { from: "P_G43", to: "P_G46" },
    { from: "P_G45", to: "P_G46" },
    { from: "P_G48", to: "P_G49" },
    { from: "P_G50", to: "P_G51" },
    { from: "P_G44", to: "P_G43" },
    { from: "P_G46", to: "P_G49" },
    { from: "P_G47", to: "P_G50" },
    { from: "P_G49", to: "P_G47" },

    { from: "G_1A", to: "P_G8" },
    { from: "G_1B", to: "P_G3" },
    { from: "G_CC", to: "P_G19" },
    { from: "G_5", to: "P_G48" },
    { from: "B_XEMAY", to: "P_G1" },
    { from: "B01", to: "P_G6" },
    { from: "B02", to: "P_G4" },
    { from: "B03", to: "P_G13" },
    { from: "B04", to: "P_G17" },
    { from: "B07", to: "P_G9" },
    { from: "B10", to: "P_G36" },
    { from: "B11", to: "P_G44" },
    { from: "B01_CUA1", to: "P_G6" },
    { from: "B01_CUA1", to: "B01_F1_BHYT" },
    { from: "B01_CUA2", to: "P_G14" },
    { from: "B01_CUA2", to: "B01_F1_BHYT" },
    { from: "B01", to: "B01_CUA1" },
    { from: "B02_CUA1", to: "P_G4" },
    { from: "B02_CUA1", to: "B02_F1_XQUANG" },
    { from: "B02_CUA2", to: "P_G13" },
    { from: "B02_CUA2", to: "B02_F1_MRI" },
    { from: "B02_CUA3", to: "P_G16" },
    { from: "B02_CUA3", to: "B02_F1_MRI" },
    { from: "B02", to: "B02_CUA1" },
    { from: "B03_TB1", to: "P_G6" },
    { from: "B03_TB2", to: "P_G4" },
    { from: "B03_TB1", to: "B03_F2_4", isElevator: true, instruction: "Đi thang bộ lên Tầng 2 - Nhà N2A" },
    { from: "B03_TB2", to: "B03_F2_4", isElevator: true, instruction: "Đi thang bộ lên Tầng 2 - Nhà N2A" },
    { from: "B06_CUA", to: "P_G16" },
    { from: "B06_CUA", to: "B06_F1_XQUANG" },
    { from: "B08_SANHA", to: "P_G30" },
    { from: "B08_SANHA", to: "B08_SANHCHINH" },
    { from: "B08_SANHB", to: "P_G64" },
	{ from: "B08_SANHB", to: "P_G40" },
	{ from: "P_G64", to: "B08_NHATHUOC1" },
	{ from: "P_G64", to: "B08_KHAMB" },
	{ from: "P_G64", to: "B08_NOIKHOA" },
	{ from: "P_G64", to: "B08_TM_NOIKHOA" },
	{ from: "P_G64", to: "B08_TM_CANLAMSANG" },

	{ from: "P_G63", to: "P_G62" },
	{ from: "P_G64", to: "P_G63" },
	{ from: "B08_SANHCHINH", to: "P_G63" },
	{ from: "P_G63", to: "B08_TM_CANLAMSANG" },

	{ from: "B08_SANHC", to: "P_G62" },
	{ from: "P_G62", to: "B08_KHAMA" },
	{ from: "P_G62", to: "B08_NGOAIKHOA" },
	{ from: "P_G62", to: "B08_TM_NGOAIKHOA" },
	{ from: "P_G62", to: "B08_TM_CANLAMSANG" },
    { from: "B08_NOIKHOA", to: "B08_KHAMA" },
    { from: "B08_NGOAIKHOA", to: "B08_KHAMB" },
    { from: "B08_SANHC", to: "P_G22" },
	{ from: "B12_CUA1", to: "P_G48" },
    { from: "B12_CUA2", to: "P_G45" },
    { from: "B12", to: "B12_CUA1" },
    { from: "B12", to: "B12_CUA2" },

    { from: "B16", to: "P_G51" },
    { from: "B08_CAPCUU", to: "P_G26" },

    { from: "B13_LOIVAO", to: "P_G45" },
  ],
};

const BUILDING_DIRECTORY = {
  B01: [
    { floor: 1, desc: "Nhà thuốc số 2 C1.1A", nodeId: "B01_F1_THUOC" },
    { floor: 1, desc: "Khu đăng ký khám dịch vụ C1.1A", nodeId: "B01_F1_DKKD" },
    { floor: 1, desc: "Khu đăng ký khám BHYT C1.1A", nodeId: "B01_F1_BHYT" },
    { floor: 1, desc: "Khu hướng dẫn C1.1A", nodeId: "B01_F1_HD" },
    { floor: 1, desc: "Khu thanh toán C1.1A", nodeId: "B01_F1_TT" },
    { floor: 2, desc: "Các phòng khám từ 1-20 C1.1A", nodeId: "B01_F2_5" },
    { floor: 3, desc: "Khu vực lấy mẫu xét nghiệm theo yêu cầu C1.1B", nodeId: "B01_F3_5" },
    { floor: 4, desc: "Khu vực Xquang, điện tim, siêu âm theo yêu cầu C1.1B", nodeId: "B01_F4_5" },
  ],
  B02: [
    { floor: 1, desc: "Khu vực Xquang C1.1A", nodeId: "B02_F1_XQUANG" },
    { floor: 1, desc: "Khu vực Cộng hưởng từ, MRI C1.1A", nodeId: "B02_F1_MRI" },
    { floor: 2, desc: "Các phòng khám C1.1A", nodeId: "B02_F2_6" },
    { floor: 3, desc: "Các phòng khám theo yêu cầu C1.1B", nodeId: "B02_F3_6" },
    { floor: 4, desc: "Khu vực nội soi theo yêu cầu C1.1B", nodeId: "B02_F4_6" },
  ],
  B03: [
    { floor: 1, desc: "Khu vực cấp phát thuốc BHYT", nodeId: "B03_F1_BHYT" },
    { floor: 2, desc: "Các phòng khám C1.1A", nodeId: "B03_F2_4" },
    { floor: 3, desc: "Các phòng khám theo yêu cầu C1.1B", nodeId: "B03_F3_4" },
    { floor: 4, desc: "Khu vực nội soi theo yêu cầu C1.1B", nodeId: "B03_F4_4" },
  ],
  B04: [
    { floor: 1, desc: "Khu vực nội soi C1.1A", nodeId: "B04" },
  ],
  B05: [
    { floor: null, desc: "Trung tâm máy gia tốc", nodeId: "B05" },
  ],
  B06: [
    { floor: 1, desc: "Khu vực Xquang, điện tim, siêu âm C1.1A", nodeId: "B06_F1_XQUANG" },
    { floor: 2, desc: "Trung tâm khám sức khoẻ định kỳ", nodeId: "B06_F2_7" },
    { floor: 3, desc: "Các phòng khám theo yêu cầu C1.1B", nodeId: "B06_F3_7" },
    { floor: 4, desc: "Khoa điều trị theo yêu cầu C1.1B", nodeId: "B06_F4_7" },
  ],
  B07: [
    { floor: null, desc: "Trung tâm thẩm mỹ", nodeId: "B07" },
  ],
  B08: [
    { floor: null, desc: "Khu Cấp cứu C1.3", nodeId: "B08_CAPCUU" },
    { floor: null, desc: "Khu khám A - Bộ đội hưu và Viettel", nodeId: "B08_KHAMA" },
    { floor: null, desc: "Khu khám B, khu thanh toán", nodeId: "B08_KHAMB" },
    { floor: null, desc: "Nhà thuốc số 1", nodeId: "B08_NHATHUOC1" },
    { floor: null, desc: "Nhà Nội khoa", nodeId: "B08_NOIKHOA" },
    { floor: null, desc: "Nhà Ngoại khoa", nodeId: "B08_NGOAIKHOA" },
    { floor: null, desc: "Khối nhà Cận lâm sàng", nodeId: "B08_TM_CANLAMSANG" },
  ],
  B09: [
    { floor: null, desc: "Viện Bảo vệ, chăm sóc sức khoẻ cán bộ Trung ương" },
  ],
  B10: [
    { floor: null, desc: "Ban Giám đốc", nodeId: "B10_SANHA" },
    { floor: null, desc: "Khối cơ quan", nodeId: "B10_SANHA" },
  ],
  B11: [
    { floor: 1, desc: "Khu khám bệnh truyền nhiễm" },
    { floor: 3, desc: "Khoa Hồi sức truyền nhiễm" },
    { floor: 4, desc: "Khoa Bệnh lây đường hô hấp" },
    { floor: 5, desc: "Khoa Bệnh lây đường tiêu hoá" },
    { floor: 6, desc: "Khoa Bệnh lây đường máu" },
  ],
  B12: [{ floor: null, desc: "Nhà để xe nhân viên" }],
  B_XEMAY: [{ floor: null, desc: "Nhà để xe máy", nodeId: "B_XEMAY" }],
  B13: [{ floor: null, desc: "Lối vào Nhà lưu trú", nodeId: "B13_LOIVAO" }],
  B14: [{ floor: null, desc: "Nhà thể thao đa năng" }],
  B15: [{ floor: null, desc: "Nhà thể thao đa năng" }],
  B16: [{ floor: null, desc: "Nhà tang lễ", nodeId: "B16" }],
};

const INDOOR_PLANS = {};
